language: generic 
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t derek158/docker-integration .

script:
    - docker run -e CI=true derek158/docker-integration npm run test