version: '3'

services: 
    app:
        stdin_open: true
        build: 
            context: .
            dockerfile: ./Dockerfile.dev
        ports: 
            - '3000:3000'
        volumes: 
            - .:/usr/app
    tests:
        stdin_open: true
        build: 
            context: .
            dockerfile: ./Dockerfile.dev
        volumes: 
            - .:/usr/app
        command: ["npm", "run", "test"]